# Pull request validation job
jobs:
  - template: ./ci/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneX_12_1
      iosVersion: 12.2
      xcodeVersion: 10.1_beta
      deviceName: "iPhone X"